Fix error in initialization.py
I was getting this error when running cnmf.fit() in single FOV (not patches) mode after pulling from master.

```python
--> 270         cnm.fit(Yr)
    271         #get results
    272         A, C, b, f, YrA, sn = cnm.A, cnm.C, cnm.b, cnm.f, cnm.YrA, cnm.sn

~/Desktop/KhakhLab/MiniscopeProject/caiman/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    423 
    424                 self.Ain, self.Cin, self.b_in, self.f_in, center = initialize_components(
--> 425                     Y, sn = sn, options_total = options, **options['init_params'])
    426 
    427             if self.only_init:  # only return values after initialization

~/Desktop/KhakhLab/MiniscopeProject/caiman/caiman/source_extraction/cnmf/initialization.py in initialize_components(Y, K, gSig, gSiz, ssub, tsub, nIter, maxIter, nb, kernel, use_hals, normalize_init, img, method, max_iter_snmf, alpha_snmf, sigma_smooth_snmf, perc_baseline_snmf, options_local_NMF, rolling_sum, rolling_length, sn, options_total, min_corr, min_pnr, deconvolve_options_init, ring_size_factor, center_psf)
    330             Y, Y_ds, max_number=K, gSiz=gSiz[0], gSig=gSig[0], min_corr=min_corr, min_pnr=min_pnr,
    331             deconvolve_options=deconvolve_options_init, ring_size_factor=ring_size_factor,
--> 332             center_psf=center_psf, options=options_total, sn=sn, nb=nb, ssub=ssub)
    333 
    334     elif method == 'sparse_nmf':

~/Desktop/KhakhLab/MiniscopeProject/caiman/caiman/source_extraction/cnmf/initialization.py in greedyROI_corr(Y, Y_ds, max_number, gSiz, gSig, center_psf, min_corr, min_pnr, seed_method, deconvolve_options, min_pixel, bd, thresh_init, ring_size_factor, nb, options, sn, save_video, video_name, ssub)
   1045         print('Compute Background Again')  # on decimated data
   1046         A_ds = downscale(np.reshape(A, dims + (-1,), order='F'), (ssub, ssub, 1))
-> 1047         A_ds = np.reshape(A_ds, (d1 * d2, K), order='F')
   1048         # background according to ringmodel
   1049         W, b0 = compute_W(Y_ds.reshape((-1, total_frames), order='F'),

~/anaconda/envs/caiman/lib/python3.6/site-packages/numpy/core/fromnumeric.py in reshape(a, newshape, order)
    230            [5, 6]])
    231     """
--> 232     return _wrapfunc(a, 'reshape', newshape, order=order)
    233 
    234 

~/anaconda/envs/caiman/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     55 def _wrapfunc(obj, method, *args, **kwds):
     56     try:
---> 57         return getattr(obj, method)(*args, **kwds)
     58 
     59     # An AttributeError occurs if the object does not have

ValueError: cannot reshape array of size 6858240 into shape (90240,81)
```

I figured out that it first In total, 82 neurons were initialized. but then thresholding components eliminating 5 empty spatial components so now we're down to 82 - 5 = 76. 90240 * 76 = 6858240 but it's trying to reshape to 81 neurons not 76.

The fix is to re-compute K; `K = C.shape[0]` after the spatial components evaluation step, because some components may get eliminated causing a divergence between the shapes of A, C and the value of K.